### PR TITLE
Only save the mutualfunds which we have as commodities

### PR DESCRIPTION
**Pull request by vHanda**
This is currently using ledger instead of hledger as the latter doesn't
provide a 'commodities' command, and requires parsing the 'stats'
command instead.

### CODE REVIEW

**Review by the-solipsist — CHANGES_REQUESTED** [review]
Given that even the `ledger commodities` command needs to be parsed, it is better to do it with hledger itself.  Given that this is a script specifically for Indian mutual funds, one should only grep for words starting with 'INF'.  Hence:

`hledger stats | grep -o '\bINF\w*' > /tmp/hledger-commodities`

**Comment by vHanda** [comment]
Fixed.

I didn't know about the `grep -o` option. I was initially trying to separate it using the IFS.

**Comment by the-solipsist** [comment]
Do you want to issue another pull request?  Otherwise, I can just make the necessary changes.

**Comment by vHanda** [comment]
I'm a bit confused about why another pull request is required? I modified that commit to include the changes.

However, whatever is easier for you. Let me know.

**Pull request merged**
